/// StorageService — Local persistence layer using Hive.
///
/// Manages three Hive boxes:
/// - `conversations` — Chat session metadata (title, timestamps).
/// - `messages` — Individual messages with role and content.
/// - `settings` — App configuration (API key, model, dark mode).
///
/// Also handles data migration when switching between API providers
/// (e.g., Gemini model names → Groq model names).
library;

import 'package:flutter/foundation.dart';
import 'package:hive/hive.dart';
import 'package:hive_flutter/hive_flutter.dart';
import '../models/conversation.dart';
import '../models/message.dart';
import '../models/app_settings.dart';

class StorageService {
  late Box<Conversation> _conversationsBox;
  late Box<Message> _messagesBox;
  late Box<AppSettings> _settingsBox;

  /// Initializes Hive and opens all required boxes.
  ///
  /// If no settings exist yet, creates default settings.
  /// If settings contain a stale Gemini model name, migrates to the
  /// Groq default (`llama-3.3-70b-versatile`).
  Future<void> init() async {
    await Hive.initFlutter();

    // Register Hive type adapters (generated by build_runner)
    Hive.registerAdapter(ConversationAdapter());
    Hive.registerAdapter(MessageAdapter());
    Hive.registerAdapter(AppSettingsAdapter());

    // Open persistent storage boxes
    _conversationsBox = await Hive.openBox<Conversation>('conversations');
    _messagesBox = await Hive.openBox<Message>('messages');
    _settingsBox = await Hive.openBox<AppSettings>('settings');

    // Create default settings on first launch
    if (_settingsBox.isEmpty) {
      await _settingsBox.put('default', AppSettings());
    } else {
      // Migrate: fix stale model names from previous API (Gemini -> Groq)
      final settings = _settingsBox.get('default')!;
      if (settings.selectedModel.startsWith('gemini')) {
        settings.selectedModel = 'llama-3.3-70b-versatile';
        await settings.save();
      }
    }
  }

  // -- Settings --

  /// Returns the current app settings.
  AppSettings getSettings() => _settingsBox.get('default')!;

  /// Persists updated settings.
  Future<void> saveSettings(AppSettings settings) => _settingsBox.put('default', settings);

  /// Listenable for the settings box (used by ValueListenableBuilder in the UI).
  ValueListenable<Box<AppSettings>> get settingsListenable => _settingsBox.listenable();

  // -- Conversations --

  /// Returns all conversations sorted by most recently updated.
  List<Conversation> getConversations() => _conversationsBox.values.toList()
    ..sort((a, b) => b.updatedAt.compareTo(a.updatedAt));

  /// Returns a single conversation by ID, or null if not found.
  Conversation? getConversation(String id) => _conversationsBox.get(id);

  /// Saves or updates a conversation.
  Future<void> saveConversation(Conversation conversation) async {
    await _conversationsBox.put(conversation.id, conversation);
  }

  /// Deletes a conversation and all its associated messages.
  Future<void> deleteConversation(String id) async {
    await _conversationsBox.delete(id);
    // Cascade delete: remove all messages belonging to this conversation
    final keys = _messagesBox.values
        .where((m) => m.conversationId == id)
        .map((m) => m.key)
        .toList();
    await _messagesBox.deleteAll(keys);
  }

  // -- Messages --

  /// Returns all messages for a conversation, sorted chronologically.
  List<Message> getMessages(String conversationId) {
    return _messagesBox.values
        .where((m) => m.conversationId == conversationId)
        .toList()
      ..sort((a, b) => a.createdAt.compareTo(b.createdAt));
  }

  /// Saves a message and updates the parent conversation's metadata.
  Future<void> saveMessage(Message message) async {
    await _messagesBox.put(message.id, message);

    // Update conversation timestamp and message count
    final conv = _conversationsBox.get(message.conversationId);
    if (conv != null) {
      conv.updatedAt = DateTime.now();
      conv.messageCount = (conv.messageCount) + 1;
      await conv.save();
    }
  }

  /// Clears all conversations and messages (keeps settings).
  Future<void> clearAllData() async {
    await _conversationsBox.clear();
    await _messagesBox.clear();
  }
}
