/// Message — A single chat message stored via Hive.
///
/// Represents one message in a conversation. Role can be:
/// - `'user'` — sent by the human.
/// - `'assistant'` — generated by the AI.
/// - `'system'` — system-level instructions.
///
/// Hive TypeId: 1.
library;

import 'package:hive/hive.dart';

part 'message.g.dart';

@HiveType(typeId: 1)
class Message extends HiveObject {
  /// Unique identifier (UUID v4).
  @HiveField(0)
  final String id;

  /// ID of the parent conversation this message belongs to.
  @HiveField(1)
  final String conversationId;

  /// Message role: 'user', 'assistant', or 'system'.
  @HiveField(2)
  final String role;

  /// The text content of the message.
  @HiveField(3)
  final String content;

  /// When the message was created.
  @HiveField(4)
  final DateTime createdAt;

  /// Actual token count from the API response (optional).
  @HiveField(5)
  final int? tokensUsed;

  Message({
    required this.id,
    required this.conversationId,
    required this.role,
    required this.content,
    required this.createdAt,
    this.tokensUsed,
  });
}
